### ISSUE TITLE
Get currently connected clients

### ISSUE THREAD

**Issue by countbytedown** [flywheelsports/hydra-router#118]
Is it possible or could there potentially be a request to the router which would provide a list of the currently connected websocket clients? As well the ability to send a broadcast message to all currently connected clients?

Additionally, I have been unable to locate a mechanism that would allow a service to send a message to a currently connected client. Is this something that could potentially be implemented or exists and I have been unable to discern?

Really great concept and architecture and I'm looking forward to working with it.

**Comment by cjus** [comment]
@countbytedown there isn't really a way to do this in hydra-router. A common use-case for the router is to place it behind a load balancer so that multiple hydra-routers are available. In that situation a single hydra-router instance wouldn't know about clients connected to other hydra-routers.

Perhaps a good way of handling your requirement might be to place a microservice behind the hydra-router which receives registration message. That way, external clients connecting to the hydra-router could send a message to the microservice that registers clients.

Part of the registration process would be to send the userID of the connected client. You can see how to get that at this gist: https://gist.github.com/cjus/985dc617db7f1b34525571433ced580b

If you'd like to brainstorm this more with other hydra users you can join us on our hydranpm slack channel (https://hydranpm.slack.com). If you're interested send me an email at cjus34@gmail.com and I'll send you an invite.

**Comment by countbytedown** [comment]
Sent a couple Emails. Thanks

**Comment by cjus** [comment]
@countbytedown Sorry about that. Did you send an email to cjus34@gmail.com ? A github email reply won't do.

**Comment by countbytedown** [comment]
I did send it...tried again

**Comment by cjus** [comment]
Your emails ended up in my spam bucket  - sorry about that. Just sent you an invite.
